// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultLoader: typeof import('./components/ui/FyLoader/DefaultLoader.vue')['default']
    Fy404View: typeof import('./components/ui/Fy404/Fy404View.vue')['default']
    FyBreadcrumb: typeof import('./components/ui/FyBreadcrumb/FyBreadcrumb.vue')['default']
    FyCirclePercent: typeof import('./components/ui/FyCirclePercent/FyCirclePercent.vue')['default']
    FyConfirm: typeof import('./components/ui/FyConfirm/FyConfirm.vue')['default']
    FyDatatable: typeof import('./components/ui/FyDatatable/FyDatatable.vue')['default']
    FyInput: typeof import('./components/ui/FyInput/FyInput.vue')['default']
    FyLoader: typeof import('./components/ui/FyLoader/FyLoader.vue')['default']
    FyModal: typeof import('./components/ui/FyModal/FyModal.vue')['default']
    FyNavbar: typeof import('./components/ui/FyNavbar/FyNavbar.vue')['default']
    FyPaging: typeof import('./components/ui/FyPaging/FyPaging.vue')['default']
    FySteps: typeof import('./components/ui/FySteps/FySteps.vue')['default']
    FyTable: typeof import('./components/ui/FyTable/FyTable.vue')['default']
    FyTabs: typeof import('./components/ui/FyTabs/FyTabs.vue')['default']
    KlbAddPaymentMethodModal: typeof import('./components/klb/KlbBilling/KlbAddPaymentMethodModal.vue')['default']
    KlbBillingHistory: typeof import('./components/klb/KlbBilling/KlbBillingHistory.vue')['default']
    KlbBlog: typeof import('./components/klb/KlbCMS/KlbBlog.vue')['default']
    KlbBlogInnerPost: typeof import('./components/klb/KlbCMS/KlbBlogInnerPost.vue')['default']
    KlbCatalog: typeof import('./components/klb/KlbOrder/KlbCatalog.vue')['default']
    KlbComments: typeof import('./components/klb/KlbCMS/KlbComments.vue')['default']
    KlbDeleteAccount: typeof import('./components/klb/KlbAccount/KlbDeleteAccount.vue')['default']
    KlbLogin: typeof import('./components/klb/KlbLogin/KlbLogin.vue')['default']
    KlbOrder: typeof import('./components/klb/KlbOrder/KlbOrder.vue')['default']
    KlbPage: typeof import('./components/klb/KlbCMS/KlbPage.vue')['default']
    KlbProcessOrderInternal: typeof import('./components/klb/KlbOrder/KlbProcessOrderInternal.vue')['default']
    KlbSupport: typeof import('./components/klb/KlbMisc/KlbSupport.vue')['default']
    KlbUpdateBillingLocation: typeof import('./components/klb/KlbBilling/KlbUpdateBillingLocation.vue')['default']
    KlbUpdateEmailModal: typeof import('./components/klb/KlbAccount/KlbUpdateEmailModal.vue')['default']
    KlbUpdatePasswordModal: typeof import('./components/klb/KlbAccount/KlbUpdatePasswordModal.vue')['default']
    KlbUserBilling: typeof import('./components/klb/KlbUser/KlbUserBilling.vue')['default']
    KlbUserLocation: typeof import('./components/klb/KlbUser/KlbUserLocation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
