name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false
    - run: pnpm install
    - run: pnpm run build:all
    - run: pnpm run build:play
    - run: sudo apt-get update -qq && DEBIAN_FRONTEND=noninteractive sudo apt-get -y install zip
    - run: zip -9r final.zip dist etc views
      working-directory: packages/playground
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: packages/playground/final.zip

  deploy:

    runs-on: ubuntu-latest
    needs: build

    env:
      API_PREFIX: "https://ws.atonline.com/_special/rest/"
      CT_HEADER: "Content-Type: application/zip"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: build
    - run: sudo apt-get update -qq && DEBIAN_FRONTEND=noninteractive sudo apt-get -y install jq curl
    - run: curl >API_INFO -s --data-urlencode "site=${DEPLOY_SITE}" --data-urlencode "token=${DEPLOY_TOKEN}" --data-urlencode "branch=${GITHUB_REF}" --data-urlencode "commit=${GITHUB_SHA}" --data-urlencode "login=${GITHUB_ACTOR}" --data-urlencode "email=$(git show -s --format=%ce "${GITHUB_SHA}")" --data-urlencode "user_id=${GITHUB_ACTOR}" --data-urlencode "user_name=$(git show -s --format=%cn "${GITHUB_SHA}")" --data-urlencode "project=https://github.com/${GITHUB_REPOSITORY}" --data-urlencode "commit_date=$(git show -s --format=%ci "${GITHUB_SHA}")" "${API_PREFIX}Site/Version:upload"
      env:
        DEPLOY_SITE: ${{ secrets.DEPLOY_SITE }}
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
    - run: cat API_INFO | jq -r .data.PUT - >API_PUT
    - run: cat API_INFO | jq -r .data.Complete - >API_COMP
    - run: curl "-#" -T "build/final.zip" -H "$CT_HEADER" "$(cat API_PUT)" >/dev/null # upload file
    - run: curl -s "${API_PREFIX}$(cat API_COMP)"; echo # notify upload complete
